apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix-agent.fullname" . }}
  labels:
    app: "{{ template "zabbix-agent.fullname" . }}"
    chart: "{{ template "zabbix.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "zabbix-agent.fullname" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "zabbix-agent.fullname" . }}"
        chart: "{{ template "zabbix.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      containers:
      - name: zabbix-agent
        image: {{ template "zabbix_agent.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ZBX_SERVER_NAME
          value: "{{ .Values.zabbix_vars.zbx_server_name }}"
        - name: ZBX_SERVER_HOST
          value: 127.0.0.1
        - name: ZBX_TIMEOUT
          value: "{{ .Values.zabbix_vars.zbx_timeout }}"
        - name: ZBX_UNSAFEUSERPARAMETERS
          value: "{{ .Values.zabbix_vars.zbx_unsafeuserparameters }}"
        - name: ZBX_ENABLEREMOTECOMMANDS
          value: "{{ .Values.zabbix_vars.zbx_enableremotecommands }}"
        - name: ZBX_LOGREMOTECOMMANDS
          value: "{{ .Values.zabbix_vars.zbx_logremotecommands }}"
        ports:
        - containerPort: 10050
          name: agent
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 10050
{{ toYaml .Values.zabbix_agent_probes.livenessProbe | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 10050
{{ toYaml .Values.zabbix_agent_probes.readinessProbe | indent 10 }}
        volumeMounts:
        - mountPath: /var/lib/zabbix/userscripts
          name: userscripts
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: userscripts
      {{- if .Values.persistence.userscripts.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.userscripts.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
