{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "zabbix-web-nginx-mysql.fullname" . }}
  labels:
    app: "{{ template "zabbix-web-nginx-mysql.fullname" . }}"
    chart: "{{ template "zabbix.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ template "zabbix-web-nginx-mysql.fullname" $ }}"
            port:
              number: 80
  {{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
