apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix-server-mysql.fullname" . }}
  labels:
    app: "{{ template "zabbix-server-mysql.fullname" . }}"
    chart: "{{ template "zabbix.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "zabbix-server-mysql.fullname" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy.zabbix_server_mysql | nindent 4 }}
  {{- end }}
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ template "zabbix-server-mysql.fullname" . }}"
        chart: "{{ template "zabbix.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{ toYaml .Values.initContainers | nindent 10 }}
      {{- end }}
      containers:
      - name: zabbix-agent
        image: {{ template "zabbix_agent.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ZBX_SERVER_HOST
          value: 127.0.0.1
        {{ range $key, $val := .Values.zabbix_vars }}
        - name: {{ $key | upper }}
          value: "{{ $val }}"
        {{ end }}
        ports:
        - containerPort: 10050
          name: agent
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 10050
{{ toYaml .Values.zabbix_agent_probes.livenessProbe | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 10050
{{ toYaml .Values.zabbix_agent_probes.readinessProbe | indent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/zabbix/userscripts
          name: zabbix
          subPath: userscripts
        {{- end }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: zabbix-server-mysql
        image: {{ template "zabbix_server_mysql.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: DB_SERVER_HOST
          value: {{ template "mariadb.fullname" . }}
        - name: DB_SERVER_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.auth.database | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mariadb.auth.username | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
        {{ range $key, $val := .Values.zabbix_vars }}
        - name: {{ $key | upper }}
          value: "{{ $val }}"
        {{ end }}
        ports:
        - name: trapper
          containerPort: 10051
        livenessProbe:
          tcpSocket:
            port: 10051
{{ toYaml .Values.zabbix_server_mysql_probes.livenessProbe | indent 10 }}
        readinessProbe:
          tcpSocket:
            port: 10051
{{ toYaml .Values.zabbix_server_mysql_probes.readinessProbe | indent 10 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/zabbix/alertscripts
          name: zabbix
          subPath: alertscripts
        - mountPath: /var/lib/zabbix/externalscripts
          name: zabbix
          subPath: externalscripts
        - mountPath: /var/lib/zabbix/enc
          name: zabbix
          subPath: enc
        - mountPath: /var/lib/zabbix/mibs
          name: zabbix
          subPath: mibs
        - mountPath: /var/lib/zabbix/modules
          name: zabbix
          subPath: modules
        - mountPath: /var/lib/zabbix/snmptraps
          name: zabbix
          subPath: snmptraps
        - mountPath: /var/lib/zabbix/ssh_keys
          name: zabbix
          subPath: ssh-keys
        - mountPath: /var/lib/zabbix/ssl/certs
          name: zabbix
          subPath: ssl-certs
        - mountPath: /var/lib/zabbix/ssl/keys
          name: zabbix
          subPath: ssl-keys
        - mountPath: /var/lib/zabbix/ssl/ssl_ca
          name: zabbix
          subPath: ssl-ssl-ca
        - mountPath: /var/lib/zabbix/userscripts
          name: zabbix
          subPath: userscripts
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: zabbix
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
      {{- end }}
      nodeSelector:
    {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
